### ISSUE TITLE
Hey Bud, sorry to ask, having an issue 

### ISSUE THREAD

**Issue by Bradford1040** [Practicalbutterfly5/ytdl#10]
Edit figured that out (the first problem, it was https issue)

This was next

16.29.11/TD getStatic: Active load: true - ExecuteService
16.29.11/E Profile Status: unknown profile 'ytdl_Clipboard_set'
16.29.11/E result: stop task (error)
16.29.11/E Error: 1
16.29.11/MacroEdit action finished exeID 1 action no 17 code 159 status: Err next 17

Im rooted on LOS 17.1

I ran it a 4th time and it went through? I think I needed to run the clipboard permission task first, (yours)

I have had permission granted for a minute lol.

I will test it and report back if any more issues 

Yeah I select the save folder, and it continue with the initial setup and when I try to save the video it says I don't have a folder to save it too in a toast

https://photos.app.goo.gl/h9A1Dzs5E3ZoLhdh9

Thats the toast, I've manually even set the YouTube folder location and still get the same error 

OK, im not sure but for some reason, the file I downloaded went to /Tasker/ytdl/tmp, but gets deleted before it gets moved, trying to figure that out now

https://photos.app.goo.gl/rFjDdUkmWioEaysQ7

Yeah it just staying at the tmp folder, its not getting moved?

I don't know what to do as I haven't gone through your entire task yet, so if you know what to do so the rest of the task doesn't get borked let me know

**Comment by Bradford1040** [comment]
Alright I think its the variable search replace regex thats the issue.

Im guessing! But when you get around let me know how to fix that,im still not sure how regex works, I've always had help with it


17.29.22/Variables doreplresult: |%info| -> |%info|
17.29.22/E Variable Search Replace: %info -> %info
17.29.22/E Variable Search Replace:  -> 
17.29.22/E Variable Search Replace: undefined variable: %info
17.29.22/E result: stop task (error)
17.29.22/E Error: 1
17.29.22/MacroEdit action finished exeID 1 action no 2 code 598 status: Err next 2

Thats the error from search replace

**Comment by Practicalbutterfly5** [comment]
Will be fixed in version 1.1, in version 1.0 some special characters in video title lead to errors.
