### ISSUE TITLE
Update tasker

### ISSUE THREAD

**Issue by Bradford1040** [Practicalbutterfly5/ytdl#13]
We got it to work,

Hope your well, and everything is good, best wishes always

Well pre mature, um report back trying other stuff

Ive had to share termus_url_opener and stuff, as the script didn't install it, still working on it

OK he had to update termux pkg's but after its installed he is only getting "failed to download"

**Comment by Bradford1040** [comment]
I just shared my XML and going to see if that helps,

Hope everything is good,

**Comment by Bradford1040** [comment]
Been a minute since I had to set up this task, and I forgot how to read lol, so looking over your tutorial, I should be able to figure it out, if I don't ill post back, but if days go by just close th issue

**Comment by Bradford1040** [comment]
OK, he is on A11 OOS rom and continues to get download failed, I am not sure why, I've been over most everything

**Comment by Practicalbutterfly5** [comment]
Was there any error installing any termux packages? Like python?

**Comment by Bradford1040** [comment]
Not sure, I got side tracked by life, but I know its still not working as far as downloading, but we got it installed fine, turned out he had never run `pkg update or apt update` stuff, so after I had him run those it installed fine, so nothing wrong with your script.

Don't close this just yet, I might be dragging my feet but do plan on working on fixing the not download issues, which is not a network issue from what I can see ATM,

**Comment by Bradford1040** [comment]
OK well I did a fresh install of my os/rom and it doesn't work for me either, I have the tasker project but it seems like the termux stuff is not getting set, nor is the youtube folder

**Comment by Practicalbutterfly5** [comment]
Are there any errors shown while installing?

**Comment by Bradford1040** [comment]
No, but I can't set the folder, input dialog seems to be the first issue, im trying a way to bypass it, its been a bit since I looked your task over, but im thinking this is the same issue the other guy is having

**Comment by Practicalbutterfly5** [comment]
Try running `apt update` first, and then run `curl https://raw.githubusercontent.com/Practicalbutterfly5/ytdl/main/installytdl > installytdl && chmod +x installytdl && bash installytdl`

**Comment by Bradford1040** [comment]
Same issue, I set/select the directory click the back arrow and that's the end of the set up, I tried it every way I can think of

**Comment by Bradford1040** [comment]
I am waiting on a bus, but after I get to where im going I'll make a screen recording, so my wording doesn't get in the way

**Comment by Practicalbutterfly5** [comment]
Ok sure, but im interested in knowing what is termux output after the installation command.

**Comment by Korpip** [comment]
Errors I am getting is permission denied access to sdcard.  Didn't want to use ~/storage/shared ?

**Comment by Bradford1040** [comment]
Just touching base,

I am waiting for a fix from joão, the issue I've been having (and the other people that I am helping) might be a tasker beta issue. Let you know soon as João does some work (dang he is so lazy).lol joking of course about him being lazy

**Comment by Bradford1040** [comment]
Error: mkdir: '/Movies': Read-only file system
mv: bad '/sdcard/Tasker/ytdl/tmp/In This Moment - 'Black Wedding feat. Rob Halford' [OFFICIAL VIDEO].mp4': No such file or directory
id : fHAi_-DOy40
command : mkdir -p "/Movies/YouTube"
mv '/sdcard/Tasker/ytdl/tmp/In This Moment - '\''Black Wedding feat. Rob Halford'\'' [OFFICIAL VIDEO].mp4' '/Movies/YouTube/'


I manually selected the file location and manually set the 'var' s got it to start downloading and i to errored out

I see read only? I don't know why that is saying that, am I forgetting something?

**Comment by Practicalbutterfly5** [comment]
%Folder_ytdl variable should be something like /storage/emulated/0/Movies/YouTube. And not "/Movies/Youtube"

**Comment by Bradford1040** [comment]
Yeah that helped lol,

I had to manually fill everything out, but I believe thats on João and a glitch in Tasker
