### ISSUE TITLE
installation script giving error on python

### ISSUE THREAD

**Issue by prorokrak** [Practicalbutterfly5/ytdl#14]
Hi, when I tried to run the install script provided in Readme, I got this warning first: 
`WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.`

And after 4 retries, I got this error: 

`Could not fetch URL https://pypi.org/simple/yt-dlp/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/yt-dlp/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping`

Here is the script I ran:
`curl https://raw.githubusercontent.com/Practicalbutterfly5/ytdl/main/installytdl | bash`

So I am stuck here.

**Comment by Practicalbutterfly5** [comment]
The error seems to be related to running older version of openssl. I am able to replicate the issue with a fresh install termux.

Simply upgrade your packages
`apt update && apt upgrade -y`

And then try to rerun the install script.

**Comment by prorokrak** [comment]
Indeed, it did tbe trick. It was exactly my situation. I had fresh installation of Termux. Thank you for your help.
